
import {firebaseConfig} from './firebase-config.js';
import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import {getAuth,GoogleAuthProvider,signInWithPopup,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import {getFirestore,collection,addDoc,getDocs,query,orderBy,serverTimestamp,doc,setDoc,limit} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const games=[
{id:'skyward-islands',name:'Skyward Islands',desc:"Explore floating worlds, solve puzzles, and discover what's above the clouds.",status:'In development',glyph:'✦',style:''},
{id:'neon-drift',name:'Neon Drift',desc:'A fast-paced reflex game set in a luminous digital world.',status:'Experiment',glyph:'⌁',style:'neon'},
{id:'project-aura',name:'Project Aura',desc:'A quiet adventure about exploration, little discoveries, and hidden places.',status:'Coming soon',glyph:'☾',style:'aura'}];
let auth,db,user=null,ready=false;
if(firebaseConfig.apiKey&&!firebaseConfig.apiKey.includes('PASTE_')){try{const a=initializeApp(firebaseConfig);auth=getAuth(a);db=getFirestore(a);ready=true;onAuthStateChanged(auth,u=>{user=u;renderCorner();renderAccount();if(document.body.dataset.page==='community')loadPosts()})}catch(e){console.error(e)}}
const status=(id,msg,err=false)=>{const e=document.getElementById(id);if(e){e.textContent=msg;e.className='status'+(err?' error':'')}};
$('#year').textContent=new Date().getFullYear();
const root=document.documentElement,toggle=$('#themeToggle'),label=$('#themeLabel');
if(localStorage.getItem('pimincgames-theme')==='light')root.dataset.theme='light';
function theme(){const l=root.dataset.theme==='light';label.textContent=l?'Dark':'Light';toggle.firstChild.textContent=l?'☾ ':'☼ '}theme();
toggle.onclick=()=>{root.dataset.theme=root.dataset.theme==='light'?'dark':'light';localStorage.setItem('pimincgames-theme',root.dataset.theme);theme()};
document.querySelector(`[data-nav="${document.body.dataset.page}"]`)?.classList.add('active');
function renderCorner(){const e=$('#authCorner');if(!e)return;e.innerHTML=user?`<a class="row" href="account.html"><span class="avatar">${user.photoURL?`<img src="${esc(user.photoURL)}">`:esc((user.displayName||'P')[0])}</span><span>${esc(user.displayName||'Account')}</span></a>`:'<a class="btn" href="account.html">Sign in</a>'}
function renderAccount(){const e=$('#accountState');if(!e)return;if(!ready){e.innerHTML='<h2>Connect accounts</h2><p class="muted">The owner needs to finish Firebase setup. Follow README.md in this download.</p>';return}if(user){e.innerHTML=`<h2>Hi, ${esc(user.displayName||'there')}!</h2><p class="muted">${esc(user.email||'')}</p><button class="btn" id="logout">Sign out</button>`;$('#logout').onclick=()=>signOut(auth)}else{e.innerHTML='<h2>Welcome</h2><p class="muted">Use Google to sign in. This site never receives your Google password.</p><button class="btn primary" id="login">G &nbsp; Continue with Google</button><div id="authStatus" class="status"></div>';$('#login').onclick=async()=>{try{await signInWithPopup(auth,new GoogleAuthProvider())}catch(e){status('authStatus',e.message,true)}}}}
async function rating(id){if(!db)return{avg:0,count:0,mine:0};const s=await getDocs(collection(db,'games',id,'ratings'));let total=0,count=0,mine=0;s.forEach(d=>{const v=+d.data().value||0;total+=v;count++;if(user&&d.id===user.uid)mine=v});return{avg:count?total/count:0,count,mine}}
function card(g,r={avg:0,count:0}){return `<article class="card"><a href="game.html?id=${g.id}"><div class="art ${g.style}">${g.glyph}</div></a><div class="eyebrow">${g.status}</div><h3><a href="game.html?id=${g.id}">${g.name}</a></h3><p>${g.desc}</p><div class="cardfoot"><span class="stars">${r.count?r.avg.toFixed(1)+' ★':'— ★'} <span class="muted">(${r.count})</span></span><a class="btn" href="game.html?id=${g.id}">Details →</a></div></article>`}
async function lists(){for(const id of ['featuredGames','allGames']){const e=$('#'+id);if(!e)continue;e.innerHTML=games.map(g=>card(g)).join('');if(db){const rs=await Promise.all(games.map(g=>rating(g.id)));e.innerHTML=games.map((g,i)=>card(g,rs[i])).join('')}}}
async function detail(){const e=$('#gameDetail');if(!e)return;const g=games.find(x=>x.id===new URLSearchParams(location.search).get('id'))||games[0];const r=await rating(g.id);e.innerHTML=`<div class="art ${g.style}" style="height:230px;font-size:5rem">${g.glyph}</div><div class="eyebrow">${g.status}</div><h1>${g.name}<span class="gradient">.</span></h1><p class="lead">${g.desc}</p><div class="panel"><h2>Community rating</h2><p><strong>${r.count?r.avg.toFixed(1):'—'} ★</strong> · ${r.count} rating(s)</p><p class="muted">${user?'Choose a half-star to five-star rating.':'Sign in to rate this game.'}</p><div id="stars">${[.5,1,1.5,2,2.5,3,3.5,4,4.5,5].map(v=>`<button class="starbtn" data-v="${v}" title="${v} stars">${r.mine>=v?'★':'☆'}<small>${v}</small></button>`).join('')}</div><div id="ratingStatus" class="status">${r.mine?'Your rating: '+r.mine+'/5':''}</div></div><a class="btn" href="games.html">← All games</a>`;$('#stars').querySelectorAll('button').forEach(b=>b.onclick=async()=>{if(!ready){status('ratingStatus','Owner must finish Firebase setup first.',true);return}if(!user){status('ratingStatus','Sign in to rate this game.',true);return}try{const v=+b.dataset.v;await setDoc(doc(db,'games',g.id,'ratings',user.uid),{uid:user.uid,value:v,updatedAt:serverTimestamp()});await detail();await lists()}catch(e){status('ratingStatus',e.message,true)}})}
async function loadPosts(){const e=$('#postFeed');if(!e)return;if(!ready){e.innerHTML='<div class="panel">Shared posts become available after Firebase setup.</div>';return}try{const s=await getDocs(query(collection(db,'posts'),orderBy('createdAt','desc'),limit(40)));e.innerHTML=s.empty?'<div class="panel">No posts yet. Start the first discussion!</div>':s.docs.map(d=>{const p=d.data();return `<article class="post"><div class="row"><span class="avatar">${p.photoURL?`<img src="${esc(p.photoURL)}">`:esc((p.displayName||'M')[0])}</span><div><strong>${esc(p.displayName||'Member')}</strong><div class="muted">${p.createdAt?.toDate?p.createdAt.toDate().toLocaleString():'Just now'}</div></div></div><h3>${esc(p.title)}</h3><div class="postbody">${esc(p.body)}</div><div id="comments-${d.id}"></div><form class="row replyform" data-id="${d.id}" style="margin-top:12px"><input class="input" name="reply" placeholder="${user?'Write a reply…':'Sign in to reply'}" maxlength="1000" required ${user?'':'disabled'}><button class="btn" ${user?'':'disabled'}>Reply</button></form><div class="status" id="replyStatus-${d.id}"></div></article>`}).join('');for(const d of s.docs){const c=await getDocs(query(collection(db,'posts',d.id,'comments'),orderBy('createdAt','asc'),limit(25)));const t=$('#comments-'+d.id);t.innerHTML=c.docs.map(x=>`<p class="muted"><strong>${esc(x.data().displayName||'Member')}:</strong> ${esc(x.data().body)}</p>`).join('')||'<p class="muted">No replies yet.</p>'}e.querySelectorAll('.replyform').forEach(f=>f.onsubmit=async ev=>{ev.preventDefault();if(!user)return;try{await addDoc(collection(db,'posts',f.dataset.id,'comments'),{body:f.reply.value.trim(),uid:user.uid,displayName:user.displayName||'Member',createdAt:serverTimestamp()});loadPosts()}catch(x){status('replyStatus-'+f.dataset.id,x.message,true)}})}catch(err){e.innerHTML='<div class="panel">Could not load feed. Check Firebase setup and Firestore rules.</div>';console.error(err)}}
$('#postForm')?.addEventListener('submit',async ev=>{ev.preventDefault();if(!ready){status('postStatus','Owner must finish Firebase setup first.',true);return}if(!user){status('postStatus','Sign in before posting.',true);return}try{await addDoc(collection(db,'posts'),{title:$('#postTitle').value.trim(),body:$('#postBody').value.trim(),uid:user.uid,displayName:user.displayName||'Member',photoURL:user.photoURL||'',createdAt:serverTimestamp()});$('#postTitle').value='';$('#postBody').value='';status('postStatus','Post published.');loadPosts()}catch(e){status('postStatus',e.message,true)}});
renderCorner();renderAccount();lists();if(document.body.dataset.page==='game')detail();if(document.body.dataset.page==='community')loadPosts();
